---
- name: Fix APT Repository Issues
  hosts: all
  become: true
  
  tasks:
    - name: Remove problematic repository entries
      ansible.builtin.shell: |
        # Remove any existing Plex repository files
        rm -f /etc/apt/sources.list.d/plexmediaserver.list
        # Find and remove any file containing Plex repository
        find /etc/apt/sources.list.d/ -type f -exec grep -l "downloads.plex.tv" {} \; 2>/dev/null | xargs -r rm -f
        # Remove any Plex entries from main sources.list
        sed -i '/downloads\.plex\.tv/d' /etc/apt/sources.list
        # Clean APT cache
        apt-get clean
        rm -rf /var/lib/apt/lists/*
      args:
        warn: false
      changed_when: true
      
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Check if APT is working correctly
      ansible.builtin.apt:
        name: aptitude
        state: present
