---
- name: Play for setting up my-osx-setup
  hosts: all
  become: true

  roles:

    - hostname
    - ssh-server
    - source-control
    - docker
    - storage-mount
    - samba
    - chrome-browser
    - joenyland.plexmediaserver

