---
- name: Play for setting up my-osx-setup
  hosts: all
  become: true

  pre_tasks:

    - name: Ensure ~/.local/bin directory exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.local/bin
        state: directory
        mode: '755'

  roles:

    - source-control
    - docker
    - vagrant
    - keepassxc

