---
- name: Play for setting up my-osx-setup
  hosts: all
  become: true

  pre_tasks:
    - name: Fix APT repository issues
      block:
        - name: Remove problematic Plex repository entries
          ansible.builtin.shell: |
            # Remove any existing Plex repository files
            rm -f /etc/apt/sources.list.d/plexmediaserver.list
            # Find and remove any file containing Plex repository
            find /etc/apt/sources.list.d/ -type f -exec grep -l "downloads.plex.tv" {} \; | xargs -r rm -f
            # Remove any Plex entries from main sources.list
            sed -i '/downloads\.plex\.tv/d' /etc/apt/sources.list
            # Clean APT cache
            apt-get clean
            rm -rf /var/lib/apt/lists/*
          args:
            warn: false
          changed_when: true
          become: true

        - name: Update APT cache
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600
          become: true

    - name: Ensure ~/.local/bin directory exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.local/bin
        state: directory
        mode: '755'

  roles:

    - hostname
    - ssh-server
    - source-control
    - docker
    - vagrant
    - keepassxc
    - keepass
    - storage-mount
    - samba
    - chrome-browser
    - plex-server

