---
- name: Add Google Chrome repository key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
    update_cache: yes
  notify: update desktop database

- name: Ensure Chrome configuration directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/google-chrome"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  when: configure_chrome | bool
