---
# Install KeePass Password Manager (original version)

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install KeePass dependencies
  ansible.builtin.apt:
    name:
      - mono-complete  # Required for running KeePass on Linux
    state: present
    install_recommends: yes
    dpkg_options: 'force-confdef,force-confold'
  register: mono_install
  retries: 5
  delay: 10
  until: mono_install is success
  become: true

- name: Fix broken packages if needed
  ansible.builtin.command: apt-get -f install
  args:
    warn: false
  when: mono_install is failed
  become: true

- name: Install KeePass password manager
  ansible.builtin.apt:
    name: keepass2
    state: present
    install_recommends: yes
    dpkg_options: 'force-confdef,force-confold'
  register: keepass_install
  retries: 5
  delay: 10
  until: keepass_install is success
  become: true

- name: Fix broken packages if needed
  ansible.builtin.command: apt-get -f install
  args:
    warn: false
  when: keepass_install is failed
  become: true

- name: Create desktop shortcut directory if it doesn't exist
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.local/share/applications"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: Create KeePass desktop shortcut
  ansible.builtin.template:
    src: keepass.desktop.j2
    dest: "/home/{{ ansible_user }}/.local/share/applications/keepass.desktop"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true
