---
- name: Ensure Samba-related packages are installed
  ansible.builtin.apt:
    name: 
      - samba
      - samba-common
      - smbclient
    state: present
    update_cache: yes

- name: Create samba group
  ansible.builtin.group:
    name: smbusers
    state: present

- name: Create samba user
  ansible.builtin.user:
    name: "{{ smb_username }}"
    groups: smbusers
    append: yes
    state: present

- name: Set samba password for user
  ansible.builtin.shell: |
    (echo "{{ smb_password }}"; echo "{{ smb_password }}") | smbpasswd -s -a "{{ smb_username }}"
  no_log: true

- name: Check filesystem type
  ansible.builtin.shell: |
    df -T "{{ smb_share_path }}" | tail -n 1 | awk '{print $2}'
  register: filesystem_type
  changed_when: false

- name: Set filesystem facts
  ansible.builtin.set_fact:
    is_non_posix_fs: "{{ 'fat' in filesystem_type.stdout.lower() or 'ntfs' in filesystem_type.stdout.lower() or 'exfat' in filesystem_type.stdout.lower() or 'vfat' in filesystem_type.stdout.lower() }}"

- name: Ensure share directory exists (POSIX filesystem)
  ansible.builtin.file:
    path: "{{ smb_share_path }}"
    state: directory
    owner: "{{ smb_username }}"
    group: smbusers
    mode: '0770'
  when: not is_non_posix_fs

- name: Ensure share directory exists (non-POSIX filesystem)
  ansible.builtin.file:
    path: "{{ smb_share_path }}"
    state: directory
  when: is_non_posix_fs

- name: Configure smb.conf file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart samba
