- name: Setup keepasxc apt repository
  ansible.builtin.apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present

- name: Install Keepassxc and related packages
  ansible.builtin.apt:
    name: keepassxc
    state: present
    update_cache: yes
  
