- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Prepare for Samba
  vars_prompt:

    - name: smb_username
      prompt: Enter a username for samba share?
      private: false

    - name: smb_password
      prompt: Enter samba share password?

    - name: smb_share_path
      prompt: Enter samba share path?

  tasks:
  
    - name: Ensure Samba-related packages are installed.
      ansible.builtin.apt:
        name: samba
        state: present
        update_cache: yes
    - name: Add samba group
      ansible.builtin.group:
        name: smbusers
        state: present
    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ smb_username }}"
        groups: smbusers
        append: yes
        create_home: no
    - name: Include role
      ansible.builtin.include_role:
        name: vladgh.samba.server
      vars:
        samba_map_to_guest: Never  
        samba_shares:
          - name: publicshare
            comment: 'Public share, writeable by all members of group ‘users’'
            public: true
            write_list: +smbusers
            group: smbusers
            browseable: true
            path: "{{ smb_share_path }}"
