---
- name: Install and configure Samba
  hosts: all
  become: true
  vars_prompt:
    - name: smb_username
      prompt: Enter a username for samba share
      private: false

    - name: smb_password
      prompt: Enter samba share password
      private: true

    - name: smb_share_path
      prompt: Enter samba share path
      private: false
  
  roles:
    - role: samba
