---
- name: Create keyring directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download and install Plex repository key
  ansible.builtin.get_url:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    dest: /tmp/PlexSign.key
    mode: '0644'
  become: true

- name: Import Plex GPG key to keyring
  ansible.builtin.shell: |
    cat /tmp/PlexSign.key | gpg --dearmor > /usr/share/keyrings/plexmediaserver.gpg
    chmod 644 /usr/share/keyrings/plexmediaserver.gpg
  args:
    creates: /usr/share/keyrings/plexmediaserver.gpg
  become: true

- name: Remove any existing Plex repository configuration
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/plexmediaserver.list"
    state: absent
  become: true

- name: Add Plex repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/plexmediaserver.gpg] https://downloads.plex.tv/repo/deb public main"
    state: present
    filename: plexmediaserver

- name: Install Plex Media Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: yes

- name: Ensure Plex service is enabled and started
  ansible.builtin.service:
    name: plexmediaserver
    state: started
    enabled: yes

- name: Ensure Plex user exists in required groups
  ansible.builtin.user:
    name: plex
    groups: media,smbusers
    append: yes
  become: true

- name: Set ACLs to ensure Plex can read media directories
  ansible.builtin.shell: "setfacl -m u:plex:rx {{ item }}"
  loop:
    - "/mnt/MediaStorage"
    - "{{ plex_movies_directory }}"
    - "{{ plex_tv_directory }}"
    - "{{ plex_music_directory }}"
    - "{{ plex_photos_directory }}"
  become: true
  changed_when: true

- name: Clear Plex library cache
  ansible.builtin.file:
    path: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache"
    state: absent
  become: true
  notify: restart plex

- name: Allow Plex through UFW
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '32400'  # Primary Plex port
    - '1900'   # DLNA discovery
    - '3005'   # Plex Companion
    - '5353'   # Bonjour/Avahi discovery
    - '8324'   # Roku control
    - '32410'  # GDM network discovery
    - '32412'  # GDM network discovery
    - '32413'  # GDM network discovery
    - '32414'  # GDM network discovery
    - '32469'  # DLNA media transfer
  notify: restart plex
